### ISSUE TITLE
finish todo app

### ISSUE THREAD

**Issue by dvc94ch** [dvc94ch/blake-db#4]
- [ ] create document
- [ ] add peer to document
- [ ] view history
- [ ] undo/redo
- [ ] dnd todo reordering
- [ ] view/resolve conflicts
- [ ] show cursors
